In [7]:
import numpy as np
a = np.array([[1, 2, 3, 4],[5,6, 7, 8, 9]])
print(a)
print(type(a))

1
<class 'numpy.ndarray'>


C:\Users\neera\AppData\Local\Temp\ipykernel_10588\4108735417.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1, 2, 3, 4],[5,6, 7, 8, 9]])


In [18]:

a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.ndim)
print(a.dtype)


3
int32


In [20]:
s= np.array(['This','Is','A','Test'])
s.dtype

dtype('<U4')

In [45]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
arr.shape = [2,2]
print(arr)

[[[[[1 2 3 4]]]]]
[[1 2]
 [3 4]]


In [68]:

for i in range(5):
    print(i)

a=np.arange(10)
b=np.linspace(0,1,7)
c=np.arange(1,10,4)
print(a)
print(b)
print(c)


0
1
2
3
4
[0 1 2 3 4 5 6 7 8 9]
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]
[1 5 9]


In [88]:
x=np.array([(1,2),(3,4)])
y=np.array([(5,6),(7,8)])

print(x,"+",y,"=",np.add(x,y))
print(np.sum(x))
print(np.subtract(y,x))
print(np.sum(x,axis=0))

[[1 2]
 [3 4]] + [[5 6]
 [7 8]] = [[ 6  8]
 [10 12]]
10
[[4 4]
 [4 4]]
[4 6]
